<?php

return [
    'global' => [
        [
            'key' => 'support_email',
            'label' => 'Email de soporte',
            'type' => 'text',
            'default' => 'soporte@stackbase.local',
            'help' => 'Contacto general visible para soporte operativo.',
        ],
        [
            'key' => 'app_banner_enabled',
            'label' => 'Banner global activo',
            'type' => 'toggle',
            'default' => false,
            'help' => 'Permite mostrar un banner global a todos los usuarios autenticados.',
        ],
        [
            'key' => 'app_banner_message',
            'label' => 'Mensaje del banner global',
            'type' => 'text',
            'default' => '',
            'help' => 'Texto breve del banner transversal del sistema.',
        ],
        [
            'key' => 'app_banner_severity',
            'label' => 'Severidad del banner global',
            'type' => 'select',
            'default' => 'info',
            'options' => [
                ['label' => 'Info', 'value' => 'info'],
                ['label' => 'Success', 'value' => 'success'],
                ['label' => 'Warning', 'value' => 'warn'],
                ['label' => 'Danger', 'value' => 'danger'],
            ],
        ],
        [
            'key' => 'feature_global_error_toasts',
            'label' => 'Toasts globales de error HTTP',
            'type' => 'toggle',
            'default' => true,
            'help' => 'Muestra feedback global cuando una llamada HTTP falla.',
        ],
        [
            'key' => 'feature_notifications_email',
            'label' => 'Canal email habilitado',
            'type' => 'toggle',
            'default' => false,
            'help' => 'Flag operativo para preparar el canal email.',
        ],
        [
            'key' => 'feature_notifications_whatsapp',
            'label' => 'Canal WhatsApp habilitado',
            'type' => 'toggle',
            'default' => false,
            'help' => 'Flag operativo para preparar el canal WhatsApp.',
        ],
        [
            'key' => 'feature_notifications_push',
            'label' => 'Canal push habilitado',
            'type' => 'toggle',
            'default' => false,
            'help' => 'Flag operativo para preparar el canal push.',
        ],
        [
            'key' => 'ui_theme_mode',
            'label' => 'Tema global del sistema',
            'type' => 'select',
            'default' => 'system',
            'options' => [
                ['label' => 'Segun el sistema', 'value' => 'system'],
                ['label' => 'Claro', 'value' => 'light'],
                ['label' => 'Oscuro', 'value' => 'dark'],
            ],
            'help' => 'Se aplica a todos los usuarios autenticados.',
        ],
        [
            'key' => 'ui_preset',
            'label' => 'Preset visual global',
            'type' => 'select',
            'default' => 'Aura',
            'options' => [
                ['label' => 'Aura', 'value' => 'Aura'],
                ['label' => 'Lara', 'value' => 'Lara'],
                ['label' => 'Nora', 'value' => 'Nora'],
            ],
            'help' => 'Controla la base visual del shell para todos los usuarios.',
        ],
        [
            'key' => 'ui_primary_color',
            'label' => 'Color primario global',
            'type' => 'select',
            'default' => 'emerald',
            'options' => [
                ['label' => 'Noir', 'value' => 'noir'],
                ['label' => 'Emerald', 'value' => 'emerald'],
                ['label' => 'Green', 'value' => 'green'],
                ['label' => 'Lime', 'value' => 'lime'],
                ['label' => 'Orange', 'value' => 'orange'],
                ['label' => 'Amber', 'value' => 'amber'],
                ['label' => 'Yellow', 'value' => 'yellow'],
                ['label' => 'Teal', 'value' => 'teal'],
                ['label' => 'Cyan', 'value' => 'cyan'],
                ['label' => 'Sky', 'value' => 'sky'],
                ['label' => 'Blue', 'value' => 'blue'],
                ['label' => 'Indigo', 'value' => 'indigo'],
                ['label' => 'Violet', 'value' => 'violet'],
                ['label' => 'Purple', 'value' => 'purple'],
                ['label' => 'Fuchsia', 'value' => 'fuchsia'],
                ['label' => 'Pink', 'value' => 'pink'],
                ['label' => 'Rose', 'value' => 'rose'],
            ],
            'help' => 'Controla el color primario del shell para todos los usuarios.',
        ],
        [
            'key' => 'ui_surface_palette',
            'label' => 'Superficie global',
            'type' => 'select',
            'default' => 'slate',
            'options' => [
                ['label' => 'Slate', 'value' => 'slate'],
                ['label' => 'Gray', 'value' => 'gray'],
                ['label' => 'Zinc', 'value' => 'zinc'],
                ['label' => 'Neutral', 'value' => 'neutral'],
                ['label' => 'Stone', 'value' => 'stone'],
                ['label' => 'Soho', 'value' => 'soho'],
                ['label' => 'Viva', 'value' => 'viva'],
                ['label' => 'Ocean', 'value' => 'ocean'],
            ],
            'help' => 'Define la paleta base de superficies del shell.',
        ],
        [
            'key' => 'ui_menu_mode',
            'label' => 'Tipo de menu global',
            'type' => 'select',
            'default' => 'static',
            'options' => [
                ['label' => 'Lateral fijo', 'value' => 'static'],
                ['label' => 'Overlay', 'value' => 'overlay'],
            ],
            'help' => 'Se aplica a toda la experiencia del shell para usuarios autenticados.',
        ],
    ],
    'organization' => [
        [
            'key' => 'locale',
            'label' => 'Locale por defecto',
            'type' => 'select',
            'default' => 'es-BO',
            'options' => [
                ['label' => 'Español (Bolivia)', 'value' => 'es-BO'],
                ['label' => 'Español (España)', 'value' => 'es-ES'],
                ['label' => 'English (US)', 'value' => 'en-US'],
            ],
        ],
        [
            'key' => 'date_format',
            'label' => 'Formato de fecha',
            'type' => 'select',
            'default' => 'DD/MM/YYYY',
            'options' => [
                ['label' => 'DD/MM/YYYY', 'value' => 'DD/MM/YYYY'],
                ['label' => 'YYYY-MM-DD', 'value' => 'YYYY-MM-DD'],
                ['label' => 'MM/DD/YYYY', 'value' => 'MM/DD/YYYY'],
            ],
        ],
        [
            'key' => 'currency_code',
            'label' => 'Moneda por defecto',
            'type' => 'select',
            'default' => 'BOB',
            'options' => [
                ['label' => 'Boliviano (BOB)', 'value' => 'BOB'],
                ['label' => 'Dólar (USD)', 'value' => 'USD'],
                ['label' => 'Euro (EUR)', 'value' => 'EUR'],
            ],
        ],
        [
            'key' => 'timezone',
            'label' => 'Zona horaria por defecto',
            'type' => 'select',
            'default' => 'America/La_Paz',
            'options' => [
                ['label' => 'America/La_Paz', 'value' => 'America/La_Paz'],
                ['label' => 'UTC', 'value' => 'UTC'],
                ['label' => 'America/New_York', 'value' => 'America/New_York'],
                ['label' => 'Europe/Madrid', 'value' => 'Europe/Madrid'],
            ],
        ],
    ],
    'user' => [
        [
            'key' => 'theme',
            'label' => 'Tema',
            'type' => 'select',
            'default' => 'system',
            'hidden' => true,
            'options' => [
                ['label' => 'System', 'value' => 'system'],
                ['label' => 'Light', 'value' => 'light'],
                ['label' => 'Dark', 'value' => 'dark'],
            ],
        ],
        [
            'key' => 'locale',
            'label' => 'Locale preferido',
            'type' => 'select',
            'default' => 'inherit',
            'options' => [
                ['label' => 'Heredar de la organizacion', 'value' => 'inherit'],
                ['label' => 'EspaÃ±ol (Bolivia)', 'value' => 'es-BO'],
                ['label' => 'EspaÃ±ol (EspaÃ±a)', 'value' => 'es-ES'],
                ['label' => 'English (US)', 'value' => 'en-US'],
            ],
        ],
        [
            'key' => 'date_format',
            'label' => 'Formato de fecha preferido',
            'type' => 'select',
            'default' => 'inherit',
            'options' => [
                ['label' => 'Heredar de la organizacion', 'value' => 'inherit'],
                ['label' => 'DD/MM/YYYY', 'value' => 'DD/MM/YYYY'],
                ['label' => 'YYYY-MM-DD', 'value' => 'YYYY-MM-DD'],
                ['label' => 'MM/DD/YYYY', 'value' => 'MM/DD/YYYY'],
            ],
        ],
        [
            'key' => 'currency_code',
            'label' => 'Moneda preferida',
            'type' => 'select',
            'default' => 'inherit',
            'options' => [
                ['label' => 'Heredar de la organizacion', 'value' => 'inherit'],
                ['label' => 'Boliviano (BOB)', 'value' => 'BOB'],
                ['label' => 'DÃ³lar (USD)', 'value' => 'USD'],
                ['label' => 'Euro (EUR)', 'value' => 'EUR'],
            ],
        ],
        [
            'key' => 'timezone',
            'label' => 'Zona horaria preferida',
            'type' => 'select',
            'default' => 'inherit',
            'options' => [
                ['label' => 'Heredar de la organizacion', 'value' => 'inherit'],
                ['label' => 'America/La_Paz', 'value' => 'America/La_Paz'],
                ['label' => 'UTC', 'value' => 'UTC'],
                ['label' => 'America/New_York', 'value' => 'America/New_York'],
                ['label' => 'Europe/Madrid', 'value' => 'Europe/Madrid'],
            ],
        ],
        [
            'key' => 'dense_tables',
            'label' => 'Tablas compactas',
            'type' => 'toggle',
            'default' => false,
        ],
        [
            'key' => 'data_engine_preferences',
            'label' => 'Preferencias del Data Engine',
            'type' => 'json',
            'default' => [],
            'hidden' => true,
        ],
        [
            'key' => 'notifications_internal',
            'label' => 'Notificaciones internas',
            'type' => 'toggle',
            'default' => true,
        ],
        [
            'key' => 'notifications_email',
            'label' => 'Notificaciones por email',
            'type' => 'toggle',
            'default' => false,
        ],
        [
            'key' => 'notifications_whatsapp',
            'label' => 'Notificaciones por WhatsApp',
            'type' => 'toggle',
            'default' => false,
        ],
        [
            'key' => 'notifications_push',
            'label' => 'Notificaciones push',
            'type' => 'toggle',
            'default' => false,
        ],
    ],
];
