<?php

use App\Models\Area;
use App\Models\AsignacionLaboral;
use App\Models\Cargo;
use App\Models\Division;
use App\Models\Empresa;
use App\Models\Equipo;
use App\Models\Oficina;
use App\Models\Organizacion;
use App\Models\Persona;
use App\Models\Sucursal;
use App\Modules\DemoPlatform\Models\DemoContact;

return [
    'organizations' => [
        'name' => 'Organizations',
        'description' => 'Organizaciones base del sistema. La decision vigente del dominio es organizacion igual a empresa.',
        'source_module' => 'core-platform',
        'permission_key' => 'tenancy.manage',
        'model' => Organizacion::class,
        'default_sort' => [
            'field' => 'nombre',
            'direction' => 'asc',
        ],
        'fields' => [
            [
                'key' => 'nombre',
                'label' => 'Nombre',
                'type' => 'text',
                'rules' => ['required', 'string', 'max:255'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'slug',
                'label' => 'Slug',
                'type' => 'text',
                'rules' => ['required', 'string', 'max:255'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'activa',
                'label' => 'Activa',
                'type' => 'boolean',
                'rules' => ['nullable', 'boolean'],
                'sortable' => true,
                'filterable' => true,
            ],
        ],
    ],
    'tenant-companies' => [
        'name' => 'Tenant Companies',
        'description' => 'Representacion tecnica transicional de empresas por tenant mientras converge el dominio hacia organizacion igual a empresa.',
        'source_module' => 'core-platform',
        'permission_key' => 'tenancy.manage',
        'model' => Empresa::class,
        'default_sort' => [
            'field' => 'nombre',
            'direction' => 'asc',
        ],
        'fields' => [
            [
                'key' => 'nombre',
                'label' => 'Nombre',
                'type' => 'text',
                'rules' => ['required', 'string', 'max:140'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'slug',
                'label' => 'Slug',
                'type' => 'text',
                'rules' => ['required', 'string', 'max:160'],
                'sortable' => true,
                'searchable' => true,
            ],
        ],
    ],
    'tenant-branches' => [
        'name' => 'Tenant Branches',
        'description' => 'Sucursales por tenant, relacionadas a empresas.',
        'source_module' => 'core-platform',
        'permission_key' => 'tenancy.manage',
        'model' => Sucursal::class,
        'default_sort' => [
            'field' => 'nombre',
            'direction' => 'asc',
        ],
        'fields' => [
            [
                'key' => 'nombre',
                'label' => 'Nombre',
                'type' => 'text',
                'rules' => ['required', 'string', 'max:140'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'slug',
                'label' => 'Slug',
                'type' => 'text',
                'rules' => ['required', 'string', 'max:160'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'empresa_id',
                'label' => 'Empresa',
                'type' => 'relation',
                'rules' => ['nullable', 'integer', 'exists:empresas,id'],
                'table' => true,
                'form' => true,
                'sortable' => false,
                'relation' => [
                    'name' => 'empresa',
                    'resource_key' => 'tenant-companies',
                    'label_field' => 'nombre',
                    'display_key' => 'empresa_id_label',
                ],
            ],
        ],
    ],
    'tenant-teams' => [
        'name' => 'Tenant Teams',
        'description' => 'Equipos por tenant para validar estructura y relaciones operativas.',
        'source_module' => 'core-platform',
        'permission_key' => 'tenancy.manage',
        'model' => Equipo::class,
        'default_sort' => [
            'field' => 'nombre',
            'direction' => 'asc',
        ],
        'fields' => [
            [
                'key' => 'nombre',
                'label' => 'Nombre',
                'type' => 'text',
                'rules' => ['required', 'string', 'max:140'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'slug',
                'label' => 'Slug',
                'type' => 'text',
                'rules' => ['required', 'string', 'max:160'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'sucursal_id',
                'label' => 'Sucursal',
                'type' => 'relation',
                'rules' => ['nullable', 'integer', 'exists:sucursales,id'],
                'table' => true,
                'form' => true,
                'relation' => [
                    'name' => 'sucursal',
                    'resource_key' => 'tenant-branches',
                    'label_field' => 'nombre',
                    'display_key' => 'sucursal_id_label',
                ],
            ],
        ],
    ],
    'offices' => [
        'name' => 'Offices',
        'description' => 'Oficinas o sucursales operativas de la organizacion activa.',
        'source_module' => 'core-platform',
        'permission_key' => 'tenancy.manage',
        'model' => Oficina::class,
        'default_sort' => [
            'field' => 'nombre',
            'direction' => 'asc',
        ],
        'fields' => [
            [
                'key' => 'nombre',
                'label' => 'Nombre',
                'type' => 'text',
                'rules' => ['required', 'string', 'max:140'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'slug',
                'label' => 'Slug',
                'type' => 'text',
                'rules' => ['required', 'string', 'max:160'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'codigo',
                'label' => 'Codigo',
                'type' => 'text',
                'rules' => ['nullable', 'string', 'max:40'],
                'sortable' => true,
            ],
            [
                'key' => 'telefono',
                'label' => 'Telefono',
                'type' => 'text',
                'rules' => ['nullable', 'string', 'max:30'],
                'searchable' => true,
            ],
            [
                'key' => 'direccion',
                'label' => 'Direccion',
                'type' => 'textarea',
                'rules' => ['nullable', 'string', 'max:255'],
                'table' => false,
            ],
            [
                'key' => 'ciudad',
                'label' => 'Ciudad',
                'type' => 'text',
                'rules' => ['nullable', 'string', 'max:120'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'pais',
                'label' => 'Pais',
                'type' => 'text',
                'rules' => ['nullable', 'string', 'max:120'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'activa',
                'label' => 'Activa',
                'type' => 'boolean',
                'rules' => ['nullable', 'boolean'],
                'sortable' => true,
                'filterable' => true,
            ],
        ],
    ],
    'people' => [
        'name' => 'People',
        'description' => 'Personas base del dominio de la organizacion activa.',
        'source_module' => 'core-platform',
        'permission_key' => 'tenancy.manage',
        'model' => Persona::class,
        'default_sort' => [
            'field' => 'nombres',
            'direction' => 'asc',
        ],
        'fields' => [
            ['key' => 'nombres', 'label' => 'Nombres', 'type' => 'text', 'rules' => ['required', 'string', 'max:120'], 'sortable' => true, 'searchable' => true],
            ['key' => 'apellido_paterno', 'label' => 'Apellido paterno', 'type' => 'text', 'rules' => ['nullable', 'string', 'max:120'], 'sortable' => true, 'searchable' => true],
            ['key' => 'apellido_materno', 'label' => 'Apellido materno', 'type' => 'text', 'rules' => ['nullable', 'string', 'max:120'], 'sortable' => true, 'searchable' => true],
            ['key' => 'documento_identidad', 'label' => 'Documento', 'type' => 'text', 'rules' => ['nullable', 'string', 'max:60'], 'searchable' => true],
            ['key' => 'telefono', 'label' => 'Telefono', 'type' => 'text', 'rules' => ['nullable', 'string', 'max:30'], 'searchable' => true],
            ['key' => 'correo', 'label' => 'Correo', 'type' => 'email', 'rules' => ['nullable', 'email', 'max:180'], 'searchable' => true],
            ['key' => 'direccion', 'label' => 'Direccion', 'type' => 'textarea', 'rules' => ['nullable', 'string', 'max:255'], 'table' => false],
            ['key' => 'sexo', 'label' => 'Sexo', 'type' => 'text', 'rules' => ['nullable', 'string', 'max:20'], 'filterable' => true],
            ['key' => 'fecha_nacimiento', 'label' => 'Fecha nacimiento', 'type' => 'date', 'rules' => ['nullable', 'date'], 'sortable' => true],
            ['key' => 'ciudad', 'label' => 'Ciudad', 'type' => 'text', 'rules' => ['nullable', 'string', 'max:120'], 'sortable' => true, 'searchable' => true],
            ['key' => 'pais', 'label' => 'Pais', 'type' => 'text', 'rules' => ['nullable', 'string', 'max:120'], 'sortable' => true, 'searchable' => true],
            ['key' => 'activa', 'label' => 'Activa', 'type' => 'boolean', 'rules' => ['nullable', 'boolean'], 'sortable' => true, 'filterable' => true],
        ],
    ],
    'divisions' => [
        'name' => 'Divisions',
        'description' => 'Divisiones de la organizacion activa.',
        'source_module' => 'core-platform',
        'permission_key' => 'tenancy.manage',
        'model' => Division::class,
        'default_sort' => [
            'field' => 'nombre',
            'direction' => 'asc',
        ],
        'fields' => [
            ['key' => 'nombre', 'label' => 'Nombre', 'type' => 'text', 'rules' => ['required', 'string', 'max:140'], 'sortable' => true, 'searchable' => true],
            ['key' => 'slug', 'label' => 'Slug', 'type' => 'text', 'rules' => ['required', 'string', 'max:160'], 'sortable' => true, 'searchable' => true],
            ['key' => 'descripcion', 'label' => 'Descripcion', 'type' => 'textarea', 'rules' => ['nullable', 'string'], 'table' => false],
            ['key' => 'activa', 'label' => 'Activa', 'type' => 'boolean', 'rules' => ['nullable', 'boolean'], 'sortable' => true, 'filterable' => true],
        ],
    ],
    'areas' => [
        'name' => 'Areas',
        'description' => 'Areas operativas de la organizacion activa.',
        'source_module' => 'core-platform',
        'permission_key' => 'tenancy.manage',
        'model' => Area::class,
        'default_sort' => [
            'field' => 'nombre',
            'direction' => 'asc',
        ],
        'fields' => [
            ['key' => 'nombre', 'label' => 'Nombre', 'type' => 'text', 'rules' => ['required', 'string', 'max:140'], 'sortable' => true, 'searchable' => true],
            ['key' => 'slug', 'label' => 'Slug', 'type' => 'text', 'rules' => ['required', 'string', 'max:160'], 'sortable' => true, 'searchable' => true],
            [
                'key' => 'division_id',
                'label' => 'Division',
                'type' => 'relation',
                'rules' => ['nullable', 'integer', 'exists:divisiones,id'],
                'table' => true,
                'form' => true,
                'relation' => [
                    'name' => 'division',
                    'resource_key' => 'divisions',
                    'label_field' => 'nombre',
                    'display_key' => 'division_id_label',
                ],
            ],
            ['key' => 'descripcion', 'label' => 'Descripcion', 'type' => 'textarea', 'rules' => ['nullable', 'string'], 'table' => false],
            ['key' => 'activa', 'label' => 'Activa', 'type' => 'boolean', 'rules' => ['nullable', 'boolean'], 'sortable' => true, 'filterable' => true],
        ],
    ],
    'positions' => [
        'name' => 'Positions',
        'description' => 'Cargos de la organizacion activa.',
        'source_module' => 'core-platform',
        'permission_key' => 'tenancy.manage',
        'model' => Cargo::class,
        'default_sort' => [
            'field' => 'nombre',
            'direction' => 'asc',
        ],
        'fields' => [
            ['key' => 'nombre', 'label' => 'Nombre', 'type' => 'text', 'rules' => ['required', 'string', 'max:140'], 'sortable' => true, 'searchable' => true],
            ['key' => 'slug', 'label' => 'Slug', 'type' => 'text', 'rules' => ['required', 'string', 'max:160'], 'sortable' => true, 'searchable' => true],
            ['key' => 'descripcion', 'label' => 'Descripcion', 'type' => 'textarea', 'rules' => ['nullable', 'string'], 'table' => false],
            ['key' => 'activa', 'label' => 'Activa', 'type' => 'boolean', 'rules' => ['nullable', 'boolean'], 'sortable' => true, 'filterable' => true],
        ],
    ],
    'work-assignments' => [
        'name' => 'Work Assignments',
        'description' => 'Asignaciones laborales por oficina, con cargo y jerarquia por contexto operativo.',
        'source_module' => 'core-platform',
        'permission_key' => 'tenancy.manage',
        'model' => AsignacionLaboral::class,
        'default_sort' => [
            'field' => 'id',
            'direction' => 'desc',
        ],
        'fields' => [
            [
                'key' => 'persona_id',
                'label' => 'Persona',
                'type' => 'relation',
                'rules' => ['required', 'integer', 'exists:personas,id'],
                'table' => true,
                'form' => true,
                'relation' => [
                    'name' => 'persona',
                    'resource_key' => 'people',
                    'label_field' => 'nombres',
                    'display_key' => 'persona_id_label',
                ],
            ],
            [
                'key' => 'user_id',
                'label' => 'Usuario',
                'type' => 'relation',
                'rules' => ['nullable', 'integer', 'exists:users,id'],
                'table' => false,
                'form' => false,
                'relation' => [
                    'name' => 'usuario',
                    'resource_key' => null,
                    'label_field' => 'email',
                    'display_key' => 'user_id_label',
                ],
            ],
            [
                'key' => 'oficina_id',
                'label' => 'Oficina',
                'type' => 'relation',
                'rules' => ['required', 'integer', 'exists:oficinas,id'],
                'table' => true,
                'form' => true,
                'relation' => [
                    'name' => 'oficina',
                    'resource_key' => 'offices',
                    'label_field' => 'nombre',
                    'display_key' => 'oficina_id_label',
                ],
            ],
            [
                'key' => 'division_id',
                'label' => 'Division',
                'type' => 'relation',
                'rules' => ['nullable', 'integer', 'exists:divisiones,id'],
                'table' => true,
                'form' => true,
                'relation' => [
                    'name' => 'division',
                    'resource_key' => 'divisions',
                    'label_field' => 'nombre',
                    'display_key' => 'division_id_label',
                ],
            ],
            [
                'key' => 'area_id',
                'label' => 'Area',
                'type' => 'relation',
                'rules' => ['nullable', 'integer', 'exists:areas,id'],
                'table' => true,
                'form' => true,
                'relation' => [
                    'name' => 'area',
                    'resource_key' => 'areas',
                    'label_field' => 'nombre',
                    'display_key' => 'area_id_label',
                ],
            ],
            [
                'key' => 'cargo_id',
                'label' => 'Cargo',
                'type' => 'relation',
                'rules' => ['nullable', 'integer', 'exists:cargos,id'],
                'table' => true,
                'form' => true,
                'relation' => [
                    'name' => 'cargo',
                    'resource_key' => 'positions',
                    'label_field' => 'nombre',
                    'display_key' => 'cargo_id_label',
                ],
            ],
            [
                'key' => 'jefe_asignacion_id',
                'label' => 'Jefe',
                'type' => 'relation',
                'rules' => ['nullable', 'integer', 'exists:asignaciones_laborales,id'],
                'table' => false,
                'form' => true,
                'relation' => [
                    'name' => 'jefeAsignacion',
                    'resource_key' => 'work-assignments',
                    'label_field' => 'id',
                    'display_key' => 'jefe_asignacion_id_label',
                ],
            ],
            [
                'key' => 'aprobador_asignacion_id',
                'label' => 'Aprobador',
                'type' => 'relation',
                'rules' => ['nullable', 'integer', 'exists:asignaciones_laborales,id'],
                'table' => false,
                'form' => true,
                'relation' => [
                    'name' => 'aprobadorAsignacion',
                    'resource_key' => 'work-assignments',
                    'label_field' => 'id',
                    'display_key' => 'aprobador_asignacion_id_label',
                ],
            ],
            ['key' => 'es_principal', 'label' => 'Principal', 'type' => 'boolean', 'rules' => ['nullable', 'boolean'], 'sortable' => true, 'filterable' => true],
            ['key' => 'estado', 'label' => 'Estado', 'type' => 'text', 'rules' => ['required', 'string', 'max:30'], 'sortable' => true, 'filterable' => true],
            ['key' => 'fecha_inicio', 'label' => 'Fecha inicio', 'type' => 'date', 'rules' => ['nullable', 'date'], 'sortable' => true],
            ['key' => 'fecha_fin', 'label' => 'Fecha fin', 'type' => 'date', 'rules' => ['nullable', 'date'], 'sortable' => true],
        ],
    ],
    'demo-contacts' => [
        'name' => 'Demo Contacts',
        'description' => 'Recurso demo del Data Engine para validar CRUD universal, filtros, busqueda, relaciones y custom fields.',
        'source_module' => 'demo-platform',
        'permission_key' => null,
        'model' => DemoContact::class,
        'default_sort' => [
            'field' => 'nombre',
            'direction' => 'asc',
        ],
        'capabilities' => [
            'create' => true,
            'update' => true,
            'delete' => true,
            'export' => true,
            'import' => true,
        ],
        'custom_fields' => [
            [
                'key' => 'segmento',
                'label' => 'Segmento',
                'type' => 'text',
                'rules' => ['nullable', 'string', 'max:120'],
            ],
            [
                'key' => 'canal_origen',
                'label' => 'Canal de origen',
                'type' => 'select',
                'rules' => ['nullable', 'in:web,referido,evento,outbound'],
                'options' => [
                    ['label' => 'Web', 'value' => 'web'],
                    ['label' => 'Referido', 'value' => 'referido'],
                    ['label' => 'Evento', 'value' => 'evento'],
                    ['label' => 'Outbound', 'value' => 'outbound'],
                ],
            ],
            [
                'key' => 'presupuesto_estimado',
                'label' => 'Presupuesto estimado',
                'type' => 'text',
                'rules' => ['nullable', 'string', 'max:40'],
            ],
        ],
        'fields' => [
            [
                'key' => 'nombre',
                'label' => 'Nombre',
                'type' => 'text',
                'rules' => ['required', 'string', 'max:120'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'email',
                'label' => 'Email',
                'type' => 'email',
                'rules' => ['nullable', 'email', 'max:180'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'telefono',
                'label' => 'Telefono',
                'type' => 'text',
                'rules' => ['nullable', 'string', 'max:40'],
                'searchable' => true,
            ],
            [
                'key' => 'empresa',
                'label' => 'Empresa textual',
                'type' => 'text',
                'rules' => ['nullable', 'string', 'max:140'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'empresa_id',
                'label' => 'Empresa relacionada',
                'type' => 'relation',
                'rules' => ['nullable', 'integer', 'exists:empresas,id'],
                'sortable' => false,
                'searchable' => false,
                'table' => true,
                'form' => true,
                'importable' => false,
                'exportable' => false,
                'relation' => [
                    'name' => 'empresaRelacion',
                    'resource_key' => 'tenant-companies',
                    'label_field' => 'nombre',
                    'display_key' => 'empresa_id_label',
                ],
            ],
            [
                'key' => 'sucursal_id',
                'label' => 'Sucursal',
                'type' => 'relation',
                'rules' => ['nullable', 'integer', 'exists:sucursales,id'],
                'table' => true,
                'form' => true,
                'importable' => false,
                'exportable' => false,
                'relation' => [
                    'name' => 'sucursalRelacion',
                    'resource_key' => 'tenant-branches',
                    'label_field' => 'nombre',
                    'display_key' => 'sucursal_id_label',
                ],
            ],
            [
                'key' => 'equipo_id',
                'label' => 'Equipo',
                'type' => 'relation',
                'rules' => ['nullable', 'integer', 'exists:equipos,id'],
                'table' => true,
                'form' => true,
                'importable' => false,
                'exportable' => false,
                'relation' => [
                    'name' => 'equipoRelacion',
                    'resource_key' => 'tenant-teams',
                    'label_field' => 'nombre',
                    'display_key' => 'equipo_id_label',
                ],
            ],
            [
                'key' => 'estado',
                'label' => 'Estado',
                'type' => 'select',
                'rules' => ['required', 'in:lead,active,inactive'],
                'sortable' => true,
                'filterable' => true,
                'options' => [
                    ['label' => 'Lead', 'value' => 'lead'],
                    ['label' => 'Activo', 'value' => 'active'],
                    ['label' => 'Inactivo', 'value' => 'inactive'],
                ],
            ],
            [
                'key' => 'prioridad',
                'label' => 'Prioridad',
                'type' => 'select',
                'rules' => ['required', 'in:low,medium,high'],
                'sortable' => true,
                'filterable' => true,
                'options' => [
                    ['label' => 'Baja', 'value' => 'low'],
                    ['label' => 'Media', 'value' => 'medium'],
                    ['label' => 'Alta', 'value' => 'high'],
                ],
            ],
            [
                'key' => 'notas',
                'label' => 'Notas',
                'type' => 'textarea',
                'rules' => ['nullable', 'string', 'max:500'],
                'table' => false,
            ],
        ],
    ],
];
