<?php

use App\Models\Empresa;
use App\Models\Equipo;
use App\Models\Sucursal;
use App\Modules\DemoPlatform\Models\DemoContact;

return [
    'tenant-companies' => [
        'name' => 'Tenant Companies',
        'description' => 'Empresas internas del tenant actual para probar estructuras multi-tenant reutilizables.',
        'source_module' => 'core-platform',
        'permission_key' => 'tenancy.manage',
        'model' => Empresa::class,
        'default_sort' => [
            'field' => 'nombre',
            'direction' => 'asc',
        ],
        'fields' => [
            [
                'key' => 'nombre',
                'label' => 'Nombre',
                'type' => 'text',
                'rules' => ['required', 'string', 'max:140'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'slug',
                'label' => 'Slug',
                'type' => 'text',
                'rules' => ['required', 'string', 'max:160'],
                'sortable' => true,
                'searchable' => true,
            ],
        ],
    ],
    'tenant-branches' => [
        'name' => 'Tenant Branches',
        'description' => 'Sucursales por tenant, relacionadas a empresas.',
        'source_module' => 'core-platform',
        'permission_key' => 'tenancy.manage',
        'model' => Sucursal::class,
        'default_sort' => [
            'field' => 'nombre',
            'direction' => 'asc',
        ],
        'fields' => [
            [
                'key' => 'nombre',
                'label' => 'Nombre',
                'type' => 'text',
                'rules' => ['required', 'string', 'max:140'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'slug',
                'label' => 'Slug',
                'type' => 'text',
                'rules' => ['required', 'string', 'max:160'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'empresa_id',
                'label' => 'Empresa',
                'type' => 'relation',
                'rules' => ['nullable', 'integer', 'exists:empresas,id'],
                'table' => true,
                'form' => true,
                'sortable' => false,
                'relation' => [
                    'name' => 'empresa',
                    'resource_key' => 'tenant-companies',
                    'label_field' => 'nombre',
                    'display_key' => 'empresa_id_label',
                ],
            ],
        ],
    ],
    'tenant-teams' => [
        'name' => 'Tenant Teams',
        'description' => 'Equipos por tenant para validar estructura y relaciones operativas.',
        'source_module' => 'core-platform',
        'permission_key' => 'tenancy.manage',
        'model' => Equipo::class,
        'default_sort' => [
            'field' => 'nombre',
            'direction' => 'asc',
        ],
        'fields' => [
            [
                'key' => 'nombre',
                'label' => 'Nombre',
                'type' => 'text',
                'rules' => ['required', 'string', 'max:140'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'slug',
                'label' => 'Slug',
                'type' => 'text',
                'rules' => ['required', 'string', 'max:160'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'sucursal_id',
                'label' => 'Sucursal',
                'type' => 'relation',
                'rules' => ['nullable', 'integer', 'exists:sucursales,id'],
                'table' => true,
                'form' => true,
                'relation' => [
                    'name' => 'sucursal',
                    'resource_key' => 'tenant-branches',
                    'label_field' => 'nombre',
                    'display_key' => 'sucursal_id_label',
                ],
            ],
        ],
    ],
    'demo-contacts' => [
        'name' => 'Demo Contacts',
        'description' => 'Recurso demo del Data Engine para validar CRUD universal, filtros, busqueda, relaciones y custom fields.',
        'source_module' => 'demo-platform',
        'permission_key' => null,
        'model' => DemoContact::class,
        'default_sort' => [
            'field' => 'nombre',
            'direction' => 'asc',
        ],
        'capabilities' => [
            'create' => true,
            'update' => true,
            'delete' => true,
            'export' => true,
            'import' => true,
        ],
        'custom_fields' => [
            [
                'key' => 'segmento',
                'label' => 'Segmento',
                'type' => 'text',
                'rules' => ['nullable', 'string', 'max:120'],
            ],
            [
                'key' => 'canal_origen',
                'label' => 'Canal de origen',
                'type' => 'select',
                'rules' => ['nullable', 'in:web,referido,evento,outbound'],
                'options' => [
                    ['label' => 'Web', 'value' => 'web'],
                    ['label' => 'Referido', 'value' => 'referido'],
                    ['label' => 'Evento', 'value' => 'evento'],
                    ['label' => 'Outbound', 'value' => 'outbound'],
                ],
            ],
            [
                'key' => 'presupuesto_estimado',
                'label' => 'Presupuesto estimado',
                'type' => 'text',
                'rules' => ['nullable', 'string', 'max:40'],
            ],
        ],
        'fields' => [
            [
                'key' => 'nombre',
                'label' => 'Nombre',
                'type' => 'text',
                'rules' => ['required', 'string', 'max:120'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'email',
                'label' => 'Email',
                'type' => 'email',
                'rules' => ['nullable', 'email', 'max:180'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'telefono',
                'label' => 'Telefono',
                'type' => 'text',
                'rules' => ['nullable', 'string', 'max:40'],
                'searchable' => true,
            ],
            [
                'key' => 'empresa',
                'label' => 'Empresa textual',
                'type' => 'text',
                'rules' => ['nullable', 'string', 'max:140'],
                'sortable' => true,
                'searchable' => true,
            ],
            [
                'key' => 'empresa_id',
                'label' => 'Empresa relacionada',
                'type' => 'relation',
                'rules' => ['nullable', 'integer', 'exists:empresas,id'],
                'sortable' => false,
                'searchable' => false,
                'table' => true,
                'form' => true,
                'importable' => false,
                'exportable' => false,
                'relation' => [
                    'name' => 'empresaRelacion',
                    'resource_key' => 'tenant-companies',
                    'label_field' => 'nombre',
                    'display_key' => 'empresa_id_label',
                ],
            ],
            [
                'key' => 'sucursal_id',
                'label' => 'Sucursal',
                'type' => 'relation',
                'rules' => ['nullable', 'integer', 'exists:sucursales,id'],
                'table' => true,
                'form' => true,
                'importable' => false,
                'exportable' => false,
                'relation' => [
                    'name' => 'sucursalRelacion',
                    'resource_key' => 'tenant-branches',
                    'label_field' => 'nombre',
                    'display_key' => 'sucursal_id_label',
                ],
            ],
            [
                'key' => 'equipo_id',
                'label' => 'Equipo',
                'type' => 'relation',
                'rules' => ['nullable', 'integer', 'exists:equipos,id'],
                'table' => true,
                'form' => true,
                'importable' => false,
                'exportable' => false,
                'relation' => [
                    'name' => 'equipoRelacion',
                    'resource_key' => 'tenant-teams',
                    'label_field' => 'nombre',
                    'display_key' => 'equipo_id_label',
                ],
            ],
            [
                'key' => 'estado',
                'label' => 'Estado',
                'type' => 'select',
                'rules' => ['required', 'in:lead,active,inactive'],
                'sortable' => true,
                'filterable' => true,
                'options' => [
                    ['label' => 'Lead', 'value' => 'lead'],
                    ['label' => 'Activo', 'value' => 'active'],
                    ['label' => 'Inactivo', 'value' => 'inactive'],
                ],
            ],
            [
                'key' => 'prioridad',
                'label' => 'Prioridad',
                'type' => 'select',
                'rules' => ['required', 'in:low,medium,high'],
                'sortable' => true,
                'filterable' => true,
                'options' => [
                    ['label' => 'Baja', 'value' => 'low'],
                    ['label' => 'Media', 'value' => 'medium'],
                    ['label' => 'Alta', 'value' => 'high'],
                ],
            ],
            [
                'key' => 'notas',
                'label' => 'Notas',
                'type' => 'textarea',
                'rules' => ['nullable', 'string', 'max:500'],
                'table' => false,
            ],
        ],
    ],
];
